//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMODS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMODS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("acBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("acBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("acBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("acBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsDown_lod0 {
            get {
                object obj = ResourceManager.GetObject("acEarsDown_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsDown_lod1 {
            get {
                object obj = ResourceManager.GetObject("acEarsDown_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsDown_lod2 {
            get {
                object obj = ResourceManager.GetObject("acEarsDown_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsDown_lod3 {
            get {
                object obj = ResourceManager.GetObject("acEarsDown_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsUp_lod0 {
            get {
                object obj = ResourceManager.GetObject("acEarsUp_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsUp_lod1 {
            get {
                object obj = ResourceManager.GetObject("acEarsUp_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsUp_lod2 {
            get {
                object obj = ResourceManager.GetObject("acEarsUp_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acEarsUp_lod3 {
            get {
                object obj = ResourceManager.GetObject("acEarsUp_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("acHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("acHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("acHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("acHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("acShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("acShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("acShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("acShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("acTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("acTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("acTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("acTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTailStub_lod0 {
            get {
                object obj = ResourceManager.GetObject("acTailStub_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTailStub_lod1 {
            get {
                object obj = ResourceManager.GetObject("acTailStub_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTailStub_lod2 {
            get {
                object obj = ResourceManager.GetObject("acTailStub_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acTailStub_lod3 {
            get {
                object obj = ResourceManager.GetObject("acTailStub_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("adBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("adBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("adBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("adBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsDown_lod0 {
            get {
                object obj = ResourceManager.GetObject("adEarsDown_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsDown_lod1 {
            get {
                object obj = ResourceManager.GetObject("adEarsDown_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsDown_lod2 {
            get {
                object obj = ResourceManager.GetObject("adEarsDown_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsDown_lod3 {
            get {
                object obj = ResourceManager.GetObject("adEarsDown_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsUp_lod0 {
            get {
                object obj = ResourceManager.GetObject("adEarsUp_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsUp_lod1 {
            get {
                object obj = ResourceManager.GetObject("adEarsUp_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsUp_lod2 {
            get {
                object obj = ResourceManager.GetObject("adEarsUp_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adEarsUp_lod3 {
            get {
                object obj = ResourceManager.GetObject("adEarsUp_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("adHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("adHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("adHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("adHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("adShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("adShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("adShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("adShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("adTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("adTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("adTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("adTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailRing_lod0 {
            get {
                object obj = ResourceManager.GetObject("adTailRing_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailRing_lod1 {
            get {
                object obj = ResourceManager.GetObject("adTailRing_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailRing_lod2 {
            get {
                object obj = ResourceManager.GetObject("adTailRing_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailRing_lod3 {
            get {
                object obj = ResourceManager.GetObject("adTailRing_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailScrew_lod0 {
            get {
                object obj = ResourceManager.GetObject("adTailScrew_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailScrew_lod1 {
            get {
                object obj = ResourceManager.GetObject("adTailScrew_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailScrew_lod2 {
            get {
                object obj = ResourceManager.GetObject("adTailScrew_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailScrew_lod3 {
            get {
                object obj = ResourceManager.GetObject("adTailScrew_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailStub_lod0 {
            get {
                object obj = ResourceManager.GetObject("adTailStub_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailStub_lod1 {
            get {
                object obj = ResourceManager.GetObject("adTailStub_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailStub_lod2 {
            get {
                object obj = ResourceManager.GetObject("adTailStub_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adTailStub_lod3 {
            get {
                object obj = ResourceManager.GetObject("adTailStub_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("alBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("alBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("alBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("alBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsDown_lod0 {
            get {
                object obj = ResourceManager.GetObject("alEarsDown_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsDown_lod1 {
            get {
                object obj = ResourceManager.GetObject("alEarsDown_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsDown_lod2 {
            get {
                object obj = ResourceManager.GetObject("alEarsDown_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsDown_lod3 {
            get {
                object obj = ResourceManager.GetObject("alEarsDown_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsUp_lod0 {
            get {
                object obj = ResourceManager.GetObject("alEarsUp_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsUp_lod1 {
            get {
                object obj = ResourceManager.GetObject("alEarsUp_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsUp_lod2 {
            get {
                object obj = ResourceManager.GetObject("alEarsUp_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alEarsUp_lod3 {
            get {
                object obj = ResourceManager.GetObject("alEarsUp_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("alHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("alHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("alHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("alHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("alShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("alShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("alShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("alShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("alTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("alTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("alTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("alTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailRing_lod0 {
            get {
                object obj = ResourceManager.GetObject("alTailRing_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailRing_lod1 {
            get {
                object obj = ResourceManager.GetObject("alTailRing_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailRing_lod2 {
            get {
                object obj = ResourceManager.GetObject("alTailRing_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailRing_lod3 {
            get {
                object obj = ResourceManager.GetObject("alTailRing_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailScrew_lod0 {
            get {
                object obj = ResourceManager.GetObject("alTailScrew_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailScrew_lod1 {
            get {
                object obj = ResourceManager.GetObject("alTailScrew_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailScrew_lod2 {
            get {
                object obj = ResourceManager.GetObject("alTailScrew_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailScrew_lod3 {
            get {
                object obj = ResourceManager.GetObject("alTailScrew_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailStub_lod0 {
            get {
                object obj = ResourceManager.GetObject("alTailStub_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailStub_lod1 {
            get {
                object obj = ResourceManager.GetObject("alTailStub_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailStub_lod2 {
            get {
                object obj = ResourceManager.GetObject("alTailStub_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alTailStub_lod3 {
            get {
                object obj = ResourceManager.GetObject("alTailStub_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blankBump {
            get {
                object obj = ResourceManager.GetObject("blankBump", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blankBump_hat {
            get {
                object obj = ResourceManager.GetObject("blankBump_hat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blankBump_necklace {
            get {
                object obj = ResourceManager.GetObject("blankBump_necklace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blankBump_pet {
            get {
                object obj = ResourceManager.GetObject("blankBump_pet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blankBump_shoes {
            get {
                object obj = ResourceManager.GetObject("blankBump_shoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blankBumpSmall {
            get {
                object obj = ResourceManager.GetObject("blankBumpSmall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankShadow {
            get {
                object obj = ResourceManager.GetObject("BlankShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankShadow_pet {
            get {
                object obj = ResourceManager.GetObject("BlankShadow_pet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankSpecular {
            get {
                object obj = ResourceManager.GetObject("BlankSpecular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankSpecular_pet {
            get {
                object obj = ResourceManager.GetObject("BlankSpecular_pet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CatSkin {
            get {
                object obj = ResourceManager.GetObject("CatSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsDown_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccEarsDown_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsDown_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccEarsDown_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsDown_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccEarsDown_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsDown_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccEarsDown_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsUp_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccEarsUp_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsUp_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccEarsUp_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsUp_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccEarsUp_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccEarsUp_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccEarsUp_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTailStub_lod0 {
            get {
                object obj = ResourceManager.GetObject("ccTailStub_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTailStub_lod1 {
            get {
                object obj = ResourceManager.GetObject("ccTailStub_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTailStub_lod2 {
            get {
                object obj = ResourceManager.GetObject("ccTailStub_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccTailStub_lod3 {
            get {
                object obj = ResourceManager.GetObject("ccTailStub_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsDown_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdEarsDown_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsDown_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdEarsDown_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsDown_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdEarsDown_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsDown_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdEarsDown_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsUp_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdEarsUp_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsUp_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdEarsUp_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsUp_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdEarsUp_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdEarsUp_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdEarsUp_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailRing_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdTailRing_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailRing_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdTailRing_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailRing_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdTailRing_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailRing_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdTailRing_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailScrew_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdTailScrew_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailScrew_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdTailScrew_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailScrew_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdTailScrew_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailScrew_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdTailScrew_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailStub_lod0 {
            get {
                object obj = ResourceManager.GetObject("cdTailStub_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailStub_lod1 {
            get {
                object obj = ResourceManager.GetObject("cdTailStub_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailStub_lod2 {
            get {
                object obj = ResourceManager.GetObject("cdTailStub_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cdTailStub_lod3 {
            get {
                object obj = ResourceManager.GetObject("cdTailStub_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChildSkin {
            get {
                object obj = ResourceManager.GetObject("ChildSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChildUnderwear {
            get {
                object obj = ResourceManager.GetObject("ChildUnderwear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("cuBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("cuBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("cuBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("cuBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBottom_lod0 {
            get {
                object obj = ResourceManager.GetObject("cuBottom_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBottom_lod1 {
            get {
                object obj = ResourceManager.GetObject("cuBottom_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBottom_lod2 {
            get {
                object obj = ResourceManager.GetObject("cuBottom_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuBottom_lod3 {
            get {
                object obj = ResourceManager.GetObject("cuBottom_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("cuHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("cuHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("cuHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("cuHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("cuShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("cuShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("cuShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("cuShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuSkirt_lod0 {
            get {
                object obj = ResourceManager.GetObject("cuSkirt_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuSkirt_lod1 {
            get {
                object obj = ResourceManager.GetObject("cuSkirt_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuSkirt_lod2 {
            get {
                object obj = ResourceManager.GetObject("cuSkirt_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuSkirt_lod3 {
            get {
                object obj = ResourceManager.GetObject("cuSkirt_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuTop_lod0 {
            get {
                object obj = ResourceManager.GetObject("cuTop_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuTop_lod1 {
            get {
                object obj = ResourceManager.GetObject("cuTop_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuTop_lod2 {
            get {
                object obj = ResourceManager.GetObject("cuTop_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cuTop_lod3 {
            get {
                object obj = ResourceManager.GetObject("cuTop_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DogSkin {
            get {
                object obj = ResourceManager.GetObject("DogSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] empty_image {
            get {
                object obj = ResourceManager.GetObject("empty_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FemaleSkin {
            get {
                object obj = ResourceManager.GetObject("FemaleSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FemaleUnderwear {
            get {
                object obj = ResourceManager.GetObject("FemaleUnderwear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaleSkin {
            get {
                object obj = ResourceManager.GetObject("MaleSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaleUnderwear {
            get {
                object obj = ResourceManager.GetObject("MaleUnderwear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NullImage {
            get {
                object obj = ResourceManager.GetObject("NullImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("puBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("puBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("puBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("puBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBottom_lod0 {
            get {
                object obj = ResourceManager.GetObject("puBottom_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBottom_lod1 {
            get {
                object obj = ResourceManager.GetObject("puBottom_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBottom_lod2 {
            get {
                object obj = ResourceManager.GetObject("puBottom_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puBottom_lod3 {
            get {
                object obj = ResourceManager.GetObject("puBottom_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("puHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("puHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("puHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("puHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("puShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("puShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("puShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("puShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puTop_lod0 {
            get {
                object obj = ResourceManager.GetObject("puTop_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puTop_lod1 {
            get {
                object obj = ResourceManager.GetObject("puTop_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puTop_lod2 {
            get {
                object obj = ResourceManager.GetObject("puTop_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] puTop_lod3 {
            get {
                object obj = ResourceManager.GetObject("puTop_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBottom_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfBottom_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBottom_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfBottom_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBottom_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfBottom_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfBottom_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfBottom_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfHairReference {
            get {
                object obj = ResourceManager.GetObject("yfHairReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfSkirt_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfSkirt_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfSkirt_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfSkirt_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfSkirt_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfSkirt_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfSkirt_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfSkirt_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTop_lod0 {
            get {
                object obj = ResourceManager.GetObject("yfTop_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTop_lod1 {
            get {
                object obj = ResourceManager.GetObject("yfTop_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTop_lod2 {
            get {
                object obj = ResourceManager.GetObject("yfTop_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yfTop_lod3 {
            get {
                object obj = ResourceManager.GetObject("yfTop_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBody_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymBody_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBody_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymBody_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBody_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymBody_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBody_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymBody_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBottom_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymBottom_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBottom_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymBottom_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBottom_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymBottom_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymBottom_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymBottom_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymHead_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymHead_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymHead_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymHead_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymHead_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymHead_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymHead_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymHead_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymShoes_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymShoes_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymShoes_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymShoes_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymShoes_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymShoes_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymShoes_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymShoes_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymSkirt_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymSkirt_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymSkirt_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymSkirt_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymSkirt_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymSkirt_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymSkirt_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymSkirt_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTail_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymTail_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTail_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymTail_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTail_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymTail_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTail_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymTail_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTop_lod0 {
            get {
                object obj = ResourceManager.GetObject("ymTop_lod0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTop_lod1 {
            get {
                object obj = ResourceManager.GetObject("ymTop_lod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTop_lod2 {
            get {
                object obj = ResourceManager.GetObject("ymTop_lod2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ymTop_lod3 {
            get {
                object obj = ResourceManager.GetObject("ymTop_lod3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
